name: auto-update-news
on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install feedparser beautifulsoup4 requests lxml pillow
      - run: python news.py
      - run: |
          git config --global user.name "Gaurav Sharma Bot"
          git config --global user.email "bot@4thpillarnews.com"
          git add news.json images/
          git commit -m "auto update every 2 min" || exit 0
          git push
