name: Auto News Update
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install feedparser
      - run: python bot.py
      - run: |
          git config --global user.name "Gaurav Sharma"
          git config --global user.email "gaurav@4thpillarnews.com"
          git add news.json
          git diff --cached --quiet && echo "No change" || (git commit -m "news update" && git push)
