on:
  schedule:
    - cron: '0 * * * *' # har ghante
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.9' }
      - run: pip install feedparser
      - run: python bot.py
      - run: |
          git config user.name "Gaurav Sharma"
          git config user.email "4thpillarnews@github.com"
          git add news.json
          git commit -m "auto update hindi news" || exit 0
          git push
